version: "3.0"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5404:5432"
    environment:
      POSTGRES_DB: funderingen
      POSTGRES_USER: funderingen
      POSTGRES_PASSWORD: insecure

  web:
    build: src/
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "funderingen.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      SECRET_KEY: insecure
      DATABASE_NAME: funderingen
      DATABASE_USER: funderingen
      DATABASE_PASSWORD: insecure
